on:
  push:
    branches:
      - main

jobs:
  grading:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
      
    - name: Build, test and SonarQube Scan
      run: |
        dotnet tool install --global dotnet-sonarscanner
        dotnet tool install --global dotnet-reportgenerator-globaltool
        chmod +x .github/workflows/sonarqube.sh
        bash .github/workflows/sonarqube.sh
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
        PERSONAL_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
        PROJECT_ID: ${{ github.event.repository.name }}รง
    
    - name: Update solution
      run: |
        npm install dom-parser
        node .github/workflows/update_solution.js